# Generated by Django 6.0.7 on 2026-07-18 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text="e.g. 'The Smith Family' (admin reference only)", max_length=200)),
                ('notes', models.TextField(blank=True, help_text="Message left by the guests when they RSVP'd")),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('attendance', models.CharField(choices=[('pending', 'Pending'), ('attending', 'Attending'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('meal_choice', models.CharField(blank=True, choices=[('', 'No preference'), ('Chicken', 'Chicken'), ('Beef', 'Beef'), ('Fish', 'Fish'), ('Vegetarian', 'Vegetarian')], max_length=20)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='rsvp.party')),
            ],
        ),
    ]
